### PR TITLE
Advanced installation guide of Marzban using Docker Compose

### PR DESCRIPTION
**Pull request by harukodi**
Added a detailed guide on how to install Marzban using Docker Compose.

### CODE REVIEW

**Comment by harukodi** [comment]
Am about to add how to do vless + ws +  tls + web with caddy server to obfucate the server even more but am not really done with that documentation this is an installation method that do not require the installation script

Thanks,

**Comment by iamtheted** [comment]
okay but what do we get that we don't get when we install it through the script?

**Comment by harukodi** [comment]
To be honest nothing more than just another way of installing it. Some people want to install it with docker-compose and this would give a bit more flexibility over the container if the script have params i have not checked that

**Comment by harukodi** [comment]
Thanks am not done with the documentation yet.

**Comment by M03ED** [comment]
there is nothing advance about it 
you just generate ssl with openssl
also it have some mistakes in it , you using environment in docker file while you have a env file

**Comment by harukodi** [comment]
This is old documentation and not my updated version. There is no need to update this one since it failed the merge request and the request has been declined. I have not made a new request and will not make a new one. You can close this one if you are the owner of this repository. My new documentation also shows how to use a custom Xray version with Marzban. The environment variables have been moved to an `env` file; it is not `.env`, just `env`. I am not willing to make a new request, so this one can be closed as I mentioned earlier. Thanks for your nicely written response!

**Comment by harukodi** [comment]
The reason this has been stalled is due to personal matters in my life. Free to close it! my documentation is public on github so people are free to check my repo. Thanks!

**Comment by harukodi** [comment]
No problem but why this happened was due to changes in the marzban software which invalidated my documentation. I totally agree with you tho! Thanks

**Comment by harukodi** [comment]
https://github.com/harukodi/IT-docu/blob/main/Docker-installations/Install%20marzban%20xray%20with%20docker-compose%20advanced.md

**Pull request closed without merging**
